INSERT INTO clients (name, legal_name, trade_name, cnpj, status, segment, client_type, phone, email, address, address_number, neighborhood, city, state, zip_code, purchase_potential, notes, created_at, updated_at) VALUES
(
      'ABSOLUTA EQUIPAMENTOS DE SEGURANCA E SERVICOS LTDA',
      'ABSOLUTA EQUIPAMENTOS DE SEGURANCA E SERVICOS LTDA',
      'ABSOLUTA EQUIPAMENTOS DE SEGURANCA E SERVICOS LTDA',
      '13.078.005/0001-89',
      'active',
      'revenda',
      'PJ',
      '(64) 3432-5000',
      NULL,
      'Avenida Afonso Pena',
      '24-A',
      'Setor Central',
      'Itumbiara',
      'GO',
      '75503-380',
      'alto',
      'ID Legado Pedidos: 228684 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/13078005000189-ABSOLUTA-EQUIPAMENTOS-DE-SEGURANCA-E-SERVICOS-LTDA',
      NOW(),
      NOW()
    ),
(
      'AÇÃO SEGURA',
      'ACAO SEGURA COMERCIO E SERVICOS LTDA',
      'AÇÃO SEGURA',
      '20.494.824/0001-72',
      'active',
      'revenda',
      'PJ',
      '(61) 98621-8444',
      'contato@acaosegura.com',
      'Rua 99, Quadra85 Lote 05 Sala 01',
      'S/N',
      'Setor Zona Sul Nova',
      'Cristalina',
      'GO',
      '73850-000',
      'baixo',
      'ID Legado Pedidos: 290148 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Empresa existe (site acaosegura.com, Cristalina-GO) mas CNPJ nao encontrado em fontes indexadas | Fonte Econodata/Receita: https://www.acaosegura.com/',
      NOW(),
      NOW()
    ),
(
      'A Resende',
      'ADRIANO DIAS RESENDE E CIA LTDA',
      'A Resende',
      '14.196.871/0001-37',
      'active',
      'revenda',
      'PJ',
      '(64) 3651-5637 / (64) 98457-5514',
      'financeiroaresende@hotmail.com',
      'Avenida Leocádio de Souza Reis - Quadra H Lote 10',
      '17',
      'Sol Nascente',
      'Quirinópolis',
      'GO',
      '75863-002',
      'alto',
      'ID Legado Pedidos: 355272 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: Nome fantasia: A Resende | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/14196871000137-ADRIANO-DIAS-RESENDE-E-CIA-LTDA',
      NOW(),
      NOW()
    ),
(
      'CL Ferramentas',
      'AGUILERA OLIVEIRA FERRAMENTAS E PROTECAO LTDA',
      'CL Ferramentas',
      '04.289.731/0001-50',
      'active',
      'revenda',
      'PJ',
      '(62) 3932-4545',
      'gerencia.financeiro@clferramentas.com.br',
      'Alameda Cascavel - Quadra H Lote 13',
      '844',
      'Setor Sol Nascente',
      'Goiânia',
      'GO',
      '74210-125',
      'alto',
      'ID Legado Pedidos: 203075 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Observações: Nome fantasia: CL Ferramentas | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/aguilera-oliveira-ferramentas-e-protecao-ltda-04289731000150',
      NOW(),
      NOW()
    ),
(
      'ALFA EPI EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA',
      'ALFA EPI EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA',
      'ALFA EPI EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA',
      '50.007.338/0001-43',
      'active',
      'revenda',
      'PJ',
      '(62) 98575-5626',
      'alfaepi.compras@gmail.com',
      'Avenida Valência - Quadra 33 Lote 23',
      '853',
      'Setor Três Marias I',
      'Goiânia',
      'GO',
      '74369-620',
      'alto',
      'ID Legado Pedidos: 826541 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/alfa-epi-equipamentos-de-protecao-individual-ltda-50007338000143',
      NOW(),
      NOW()
    ),
(
      'Protseg Consultoria em Seguranca do Trabalho',
      'ANDRIOLLI PIO GONCALVES - PROTSEG',
      'Protseg Consultoria em Seguranca do Trabalho',
      '31.970.515/0001-48',
      'active',
      'revenda',
      'PJ',
      '(61) 99606-8073',
      'elizangela.protseg@gmail.com',
      'Rua Cambuí - Quadra 2 Lote 9 Loja 1',
      'S/N',
      'Setor Belvedere',
      'Cristalina',
      'GO',
      '73850-000',
      'alto',
      'ID Legado Pedidos: 476690 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 7 | Observações: Nome fantasia: Protseg Consultoria em Seguranca do Trabalho | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/31970515000148-andriolli-pio-goncalves-protseg',
      NOW(),
      NOW()
    ),
(
      'AZ FERRAGISTA LTDA',
      'AZ FERRAGISTA LTDA',
      'AZ FERRAGISTA LTDA',
      '27.466.939/0001-00',
      'active',
      'revenda',
      'PJ',
      '(62) 3202-1503 / (62) 3565-2503',
      'contagem.geral@hotmail.com',
      'Avenida Presidente Kennedy - Quadra 50 Lote 07',
      '1606',
      'Vila Jardim São Judas Tadeu',
      'Goiânia',
      'GO',
      '74685-830',
      'alto',
      'ID Legado Pedidos: 7997724 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Observações: Melhor candidata: AZ FERRAGISTA LTDA, marca ''''Azfer Ferragista'''' (azfer.com.br); possivel alteracao de razao social; email possivelmente da contabilidade | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/az-ferragista-ltda-27466939000100',
      NOW(),
      NOW()
    ),
(
      'BAIFER DISTRIBUIDORA DE FERRAMENTAS LTDA',
      'BAIFER DISTRIBUIDORA DE FERRAMENTAS LTDA',
      'BAIFER DISTRIBUIDORA DE FERRAMENTAS LTDA',
      '52.005.382/0001-40',
      'active',
      'revenda',
      'PJ',
      '(61) 98594-4960',
      'administrativo@baiferdistribuidora.com.br',
      'Setor SHA Conjunto 4 Chácara 87 - Lote 87',
      '87',
      'Setor Habitacional Arniqueira (Águas Claras)',
      'Brasília',
      'DF',
      '71994-505',
      'alto',
      'ID Legado Pedidos: 259845 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: Loja fisica em Aguas Claras/DF | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/52005382000140-BAIFER-DISTRIBUIDORA-DE-FERRAMENTAS-LTDA',
      NOW(),
      NOW()
    ),
(
      'BRAGO DISTRIBUIDORA DE PRODUTOS DE CONSUMO LTDA',
      'BRAGO DISTRIBUIDORA DE PRODUTOS DE CONSUMO LTDA',
      'BRAGO DISTRIBUIDORA DE PRODUTOS DE CONSUMO LTDA',
      '57.650.492/0001-88',
      'active',
      'revenda',
      'PJ',
      '(61) 3204-9000',
      'expediente@gomidecontabilidade.com.br',
      'Área ADE Conjunto 1 - Lote 07',
      '07',
      'Área de Desenvolvimento Econômico (Águas Claras)',
      'Brasília',
      'DF',
      '71985-000',
      'alto',
      'ID Legado Pedidos: 7996870 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Matriz em Brasilia; possui filiais (ex. 0004-20 em Goiania) | Fonte Econodata/Receita: https://empresas.serasaexperian.com.br/consulta-gratis/BRAGO-DISTRIBUIDORA-DE-PRODUTOS-DE-CONSUMO-LTDA-57650492000188',
      NOW(),
      NOW()
    ),
(
      'ADP Comercio',
      'CARLOS RAMALHO SOARES COMERCIO - ME',
      'ADP Comercio',
      '03.326.308/0001-10',
      'active',
      'revenda',
      'PJ',
      NULL,
      NULL,
      'Rua Roraima - Qd. 03 Lt. 03 C-02',
      '20',
      'Urias Magalhães',
      'Goiânia',
      'GO',
      '74565-360',
      'alto',
      'ID Legado Pedidos: 446386 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: Nome fantasia: ADP Comercio | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/carlos-ramalho-soares-comercio-03326308000110',
      NOW(),
      NOW()
    ),
(
      'CASA DA PROTECAO COMERCIO DE E.P.I S E FERRAGENS LTDA',
      'CASA DA PROTECAO COMERCIO DE E.P.I S E FERRAGENS LTDA',
      'CASA DA PROTECAO COMERCIO DE E.P.I S E FERRAGENS LTDA',
      '06.977.669/0001-14',
      'active',
      'revenda',
      'PJ',
      '(62) 3291-2293',
      NULL,
      'Avenida C 1 - Qd 08 Lt 06',
      '737',
      'Jardim America',
      'Goiânia',
      'GO',
      '74265-010',
      'alto',
      'ID Legado Pedidos: 183665 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Fonte Econodata/Receita: https://www.solutudo.com.br/empresas/go/goiania/epi-equipamentos-de-protecao-individual/casa-da-protecao-5172135',
      NOW(),
      NOW()
    ),
(
      'CONDOR ATACADISTA DE MATERIAIS PARA CONSTRUCAO S/A',
      'CONDOR ATACADISTA DE MATERIAIS PARA CONSTRUCAO S/A',
      'CONDOR ATACADISTA DE MATERIAIS PARA CONSTRUCAO S/A',
      '03.261.204/0001-74',
      'active',
      'revenda',
      'PJ',
      '(61) 2107-8800',
      'senildo@condorbrasil.com.br',
      'Setor SCIA Quadra 13 Conjunto 1 Lotes 8/9',
      'S/N',
      'Zona Industrial (Guará)',
      'Brasília',
      'DF',
      '71250-210',
      'alto',
      'ID Legado Pedidos: 826193 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Matriz em Brasilia; empresa possui varias filiais | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/03261204000174-condor-atacadista-de-materiais-para-construcao-sa',
      NOW(),
      NOW()
    ),
(
      'CRISTALINA PROTECAO PROFISSIONAL LTDA - EPP',
      'CRISTALINA PROTECAO PROFISSIONAL LTDA - EPP',
      'CRISTALINA PROTECAO PROFISSIONAL LTDA - EPP',
      '46.846.463/0001-70',
      'active',
      'revenda',
      'PJ',
      '(61) 98621-8444',
      'cristalinaprotecaoprofissional@gmail.com',
      'Rua Wilson Rodrigues Afonseca - Quadra 03 Lote 255-A Loja 01',
      '410',
      'Setor Oeste II',
      'Cristalina',
      'GO',
      '73850-000',
      'alto',
      'ID Legado Pedidos: 816818 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: Possivel alteracao de razao social para CRISTALINA CONSULTORIA E VENDAS LTDA (mesmo CNPJ) | Fonte Econodata/Receita: https://empresas.serasaexperian.com.br/consulta-gratis/CRISTALINA-CONSULTORIA-E-VENDAS-LTDA-46846463000170',
      NOW(),
      NOW()
    ),
(
      'CRS COMERCIO E REPRESENTACAO LTDA',
      'CRS COMERCIO E REPRESENTACAO LTDA',
      'CRS COMERCIO E REPRESENTACAO LTDA',
      '37.048.543/0001-99',
      'active',
      'revenda',
      'PJ',
      '(62) 3250-8400 / (62) 3286-5428',
      'crscomercio@terra.com.br',
      'Avenida C-104 - Qd. 258 Lt. 9',
      '588',
      'Jardim América',
      'Goiânia',
      'GO',
      '74250-030',
      'alto',
      'ID Legado Pedidos: 196196 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Matriz 0001-99; existe filial 0002-70 tambem em Goiania | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/37048543000199-CRS-COMERCIO-E-REPRESENTACAO-LTDA',
      NOW(),
      NOW()
    ),
(
      'DELTA COMERCIO',
      'DELTA COMERCIO E NEGOCIOS LTDA',
      'DELTA COMERCIO',
      '55.049.717/0001-10',
      'active',
      'revenda',
      'PJ',
      '(64) 99943-0829',
      'deltacomercioedistribuicao@gmail.com',
      'R 15',
      '309',
      'Jd Goias',
      'Rio Verde',
      'GO',
      '75903-420',
      'alto',
      'ID Legado Pedidos: 7997118 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 6 | Observações: Nao encontrado; nenhuma correspondencia exata nas bases indexadas',
      NOW(),
      NOW()
    ),
(
      'DELTA EQUIPAMENTOS DE SEGURANCA LTDA',
      'DELTA EQUIPAMENTOS DE SEGURANCA LTDA',
      'DELTA EQUIPAMENTOS DE SEGURANCA LTDA',
      '09.026.756/0001-84',
      'active',
      'revenda',
      'PJ',
      '(62) 3093-1112 / (62) 99156-1510',
      'loja.delta4@gmail.com',
      'Avenida Sonnemberg - Quadra 147 Lote 22',
      '470',
      'Cidade Jardim',
      'Goiânia',
      'GO',
      '74413-125',
      'alto',
      'ID Legado Pedidos: 202820 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/09026756000184-delta-equipamentos-de-seguranca-ltda',
      NOW(),
      NOW()
    ),
(
      'DF Atacadista',
      'DF COMERCIO ATACADISTA DE MATERIAIS ELETRICOS LTDA',
      'DF Atacadista',
      '33.578.308/0001-78',
      'active',
      'revenda',
      'PJ',
      '(61) 3548-0006',
      'compras@dfatacadista.com.br',
      'Trecho SIA Trecho 4 Lotes 440 e 450',
      'S/N',
      'Zona Industrial (Guará)',
      'Brasília',
      'DF',
      '71200-040',
      'alto',
      'ID Legado Pedidos: 743469 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Observações: Nome fantasia: DF Atacadista; matriz 0001-78 e filial 0002-59 ambas em Brasilia | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/df-comercio-atacadista-de-materiais-eletricos-ltda-33578308000178',
      NOW(),
      NOW()
    ),
(
      'DF EPI COMERCIO DE EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA - EPP',
      'DF EPI COMERCIO DE EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA - EPP',
      'DF EPI COMERCIO DE EQUIPAMENTOS DE PROTECAO INDIVIDUAL LTDA - EPP',
      '51.077.795/0001-77',
      'active',
      'revenda',
      'PJ',
      '(61) 3541-7819',
      'contato@dfepi.com.br',
      'Quadra CND 6 - Lote 02, Loja 02',
      '02',
      'Taguatinga Norte (Taguatinga)',
      'Brasília',
      'DF',
      '72120-065',
      'alto',
      'ID Legado Pedidos: 851761 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/51077795000177-DF-EPI-COMERCIO-DE-EQUIPAMENTOS-DE-PROTECAO-INDIVIDUAL-LTDA',
      NOW(),
      NOW()
    ),
(
      'ELETROSOLDA MAQUINAS E FERRAMENTAS LTDA',
      'ELETROSOLDA MAQUINAS E FERRAMENTAS LTDA',
      'ELETROSOLDA MAQUINAS E FERRAMENTAS LTDA',
      '01.702.695/0001-16',
      'active',
      'revenda',
      'PJ',
      '(64) 3432-5000',
      'eletrosolda@eletrosolda.com',
      'Praça da Bandeira',
      '293',
      'Centro',
      'Itumbiara',
      'GO',
      '75503-520',
      'alto',
      'ID Legado Pedidos: 221861 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/01702695000116-eletrosolda-maquinas-e-ferramentas-ltda',
      NOW(),
      NOW()
    ),
(
      'EPIFER EPIS E FERRAMENTAS LTDA',
      'EPIFER EPIS E FERRAMENTAS LTDA',
      'EPIFER EPIS E FERRAMENTAS LTDA',
      '05.865.367/0001-91',
      'active',
      'revenda',
      'PJ',
      '(62) 3247-2676',
      'pablo@epifer.com.br',
      'Avenida Sonnemberg - Quadra 123 Lote 02',
      '100',
      'Setor Cidade Jardim',
      'Goiânia',
      'GO',
      '74413-125',
      'alto',
      'ID Legado Pedidos: 203026 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/05865367000191-epifer-epis-e-ferramentas-ltda',
      NOW(),
      NOW()
    ),
(
      'EQUISEG EQUIPAMENTOS DE SEGURANCA DO TRABALHO LTDA - ME',
      'EQUISEG EQUIPAMENTOS DE SEGURANCA DO TRABALHO LTDA - ME',
      'EQUISEG EQUIPAMENTOS DE SEGURANCA DO TRABALHO LTDA - ME',
      '00.712.884/0001-07',
      'active',
      'revenda',
      'PJ',
      NULL,
      NULL,
      'Avenida C-104 - Qd. 282 Lt. 06',
      '775',
      'Jardim América',
      'Goiânia',
      'GO',
      '74250-030',
      'alto',
      'ID Legado Pedidos: 187070 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/00712884000107-equiseg-equipamentos-de-seguranca-do-trabalho-ltda',
      NOW(),
      NOW()
    ),
(
      'Atacadão da Limpeza',
      'F. PEREIRA QUEIROZ COMERCIO E DISTRIBUICAO LTDA',
      'Atacadão da Limpeza',
      '13.184.675/0001-80',
      'active',
      'revenda',
      'PJ',
      '(61) 3036-9900',
      'dpcomercio@yahoo.com.br',
      'Quadra QI 10 Lotes 39 E',
      '41',
      'Setor Industrial (Taguatinga)',
      'Brasília',
      'DF',
      '72135-100',
      'alto',
      'ID Legado Pedidos: 740970 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nome fantasia: Atacadão da Limpeza; existe filial 0003-41 em Aparecida de Goiânia/GO | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/f-pereira-queiroz-comercio-e-distribuicao-ltda-13184675000180',
      NOW(),
      NOW()
    ),
(
      'FERMAQUI COMERCIO LTDA',
      'FERMAQUI COMERCIO LTDA',
      'FERMAQUI COMERCIO LTDA',
      '37.588.639/0001-40',
      'active',
      'revenda',
      'PJ',
      '(62) 3945-4363 / (62) 98413-3047',
      'marcio.fermaqui@gmail.com',
      'Avenida Castelo Branco - Qd.22 Lt.04',
      '4550',
      'Setor Rodoviário',
      'Goiânia',
      'GO',
      '74430-130',
      'alto',
      'ID Legado Pedidos: 201764 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/37588639000140-fermaqui-comercio-ltda',
      NOW(),
      NOW()
    ),
(
      'Lima Ferramentas',
      'FERRAGISTA BARCELOS LTDA',
      'Lima Ferramentas',
      '26.670.513/0001-01',
      'active',
      'revenda',
      'PJ',
      '(62) 3255-2025',
      'ferragistabarcelos@hotmail.com',
      'Avenida Anápolis - Quadra 022 Lote 0007',
      'S/N',
      'Parque Real de Goiânia',
      'Aparecida de Goiânia',
      'GO',
      '74910-092',
      'alto',
      'ID Legado Pedidos: 185330 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: Matriz registrada em Aparecida de Goiânia (planilha dizia Goiânia); nome fantasia Lima Ferramentas; possui filiais | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/ferragista-barcelos-ltda-26670513000101',
      NOW(),
      NOW()
    ),
(
      'Rede EPI)',
      'FERRAMENTAS PROFISSIONAIS E EQUIPAMENTOS DE SEGURANCA LTDA EM RECUPERACAO JUDICIAL',
      'Rede EPI)',
      '18.428.558/0003-08',
      'active',
      'revenda',
      'PJ',
      '(62) 99673-4356',
      'diretoria@kcabr.com.br',
      'Avenida Transbrasiliana - Quadra 201 Lote 28',
      '1245',
      NULL,
      'Goiânia',
      'GO',
      '74820-065',
      'alto',
      'ID Legado Pedidos: 225698 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 25 | Observações: Filial de Goiânia (nome fantasia Rede EPI); matriz 0001-38 em Aparecida de Goiânia | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/18428558000308-ferramentas-profissionais-e-equipamentos-de-seguranca-ltda-em-recuperacao-judicial',
      NOW(),
      NOW()
    ),
(
      'Rede EPI), mesmo grupo do código 225698',
      'FERRAMENTAS PROFISSIONAIS E EQUIPAMENTOS DE SEGURANCA LTDA EM RECUPERACAO JUDICIAL',
      'Rede EPI), mesmo grupo do código 225698',
      '18.428.558/0002-19',
      'active',
      'revenda',
      'PJ',
      '(62) 3928-4106',
      NULL,
      'Rua 5 Chácara 96 - Lote 10',
      'S/N',
      'Setor Habitacional Vicente Pires',
      'Brasília',
      'DF',
      '72006-010',
      'alto',
      'ID Legado Pedidos: 396037 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 10 | Observações: Filial de Brasília (nome fantasia Rede EPI), mesmo grupo do código 225698 | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/rede-epi-equipamentos-de-seguranca-ltda-18428558000219',
      NOW(),
      NOW()
    ),
(
      'FORTE IMPERADOR ATACADISTA DE EPI LTDA',
      'FORTE IMPERADOR ATACADISTA DE EPI LTDA',
      'FORTE IMPERADOR ATACADISTA DE EPI LTDA',
      '15.823.467/0001-09',
      'active',
      'revenda',
      'PJ',
      '(62) 3926-6920',
      'atendimento@forteimperador.com.br',
      'Rua 224 - Quadra B Lote 2B',
      '90',
      NULL,
      'Goiânia',
      'GO',
      '74643-140',
      'alto',
      'ID Legado Pedidos: 204891 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/15823467000109-forte-imperador-atacadista-de-epi-ltda',
      NOW(),
      NOW()
    ),
(
      'FORTE PARAFUSOS E FERRAMENTAS LTDA',
      'FORTE PARAFUSOS E FERRAMENTAS LTDA',
      'FORTE PARAFUSOS E FERRAMENTAS LTDA',
      '11.350.036/0001-11',
      'active',
      'revenda',
      'PJ',
      '(61) 99691-8418',
      NULL,
      'Avenida Alfredo Nasser',
      'S/N',
      'Parque Estrela Dalva I',
      'Luziânia',
      'GO',
      '72804-010',
      'alto',
      'ID Legado Pedidos: 219469 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 8 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/11350036000111-forte-parafusos-e-ferramentas-ltda',
      NOW(),
      NOW()
    ),
(
      'A Casa da Limpeza',
      'FVL SOARES LTDA',
      'A Casa da Limpeza',
      '53.715.410/0001-85',
      'active',
      'revenda',
      'PJ',
      '(62) 98169-4029',
      'acasadalimpeza01@gmail.com',
      'Avenida 1 - Lote 04 Quadra 09 Sala 1',
      '75',
      'Setor Nova Vila',
      'Goiânia',
      'GO',
      '74653-050',
      'alto',
      'ID Legado Pedidos: 843946 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nome fantasia: A Casa da Limpeza | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/53715410000185-fvl-soares-ltda',
      NOW(),
      NOW()
    ),
(
      'G.A. SILVA PARAFUSOS, MAQUINAS E FERRAMENTAS LTDA',
      'G.A. SILVA PARAFUSOS, MAQUINAS E FERRAMENTAS LTDA',
      'G.A. SILVA PARAFUSOS, MAQUINAS E FERRAMENTAS LTDA',
      '02.532.281/0001-59',
      'active',
      'revenda',
      'PJ',
      '(62) 3295-5566 / (62) 99624-3237',
      'ctb.ga@terra.com.br',
      'Rua dos Missionários - Quadra 31 Lote 19',
      '679',
      'Setor Rodoviário',
      'Goiânia',
      'GO',
      '74430-360',
      'alto',
      'ID Legado Pedidos: 330978 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: ''''G A SILVA & CIA LTDA'''' e denominacao anterior; atribuida a MATRIZ 0001-59; conferir com ERP qual estabelecimento corresponde a este codigo | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/02532281000159-ga-silva-parafusos-maquinas-e-ferramentas-ltda',
      NOW(),
      NOW()
    ),
(
      'G.A. SILVA PARAFUSOS, MAQUINAS E FERRAMENTAS LTDA',
      'G.A. SILVA PARAFUSOS, MAQUINAS E FERRAMENTAS LTDA',
      'G.A. SILVA PARAFUSOS, MAQUINAS E FERRAMENTAS LTDA',
      '02.532.281/0002-30',
      'active',
      'revenda',
      'PJ',
      '(62) 3295-5566',
      'ctb.ga@terra.com.br',
      'Avenida Pio XII',
      '18',
      NULL,
      'Goiânia',
      'GO',
      '74430-215',
      'medio',
      'ID Legado Pedidos: 242984 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Mesma raiz do codigo 330978; atribuida a FILIAL 0002-30; existem ainda filiais 0003-10 e 0004-00 em Goiania — conferir com ERP | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/ga-silva-parafusos-maquinas-e-ferramentas-ltda-02532281000230',
      NOW(),
      NOW()
    ),
(
      'Central Limp',
      'GLOBAL SERVICE LIMPEZA E CONSERVACAO LTDA',
      'Central Limp',
      '08.836.495/0001-03',
      'active',
      'revenda',
      'PJ',
      '(62) 3259-7605',
      'agr@dm.com.br',
      'Avenida T-63 - Quadra 04 Lote 45',
      '4248',
      NULL,
      'Goiânia',
      'GO',
      '74335-102',
      'alto',
      'ID Legado Pedidos: 262238 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nome fantasia: Central Limp; email possivelmente da contabilidade | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/08836495000103-global-service-limpeza-e-conservacao-ltda',
      NOW(),
      NOW()
    ),
(
      'IMPERIAL COMERCIO DE PARAFUSOS FERRAMENTAS E MAQUINAS LTDA',
      'IMPERIAL COMERCIO DE PARAFUSOS FERRAMENTAS E MAQUINAS LTDA',
      'IMPERIAL COMERCIO DE PARAFUSOS FERRAMENTAS E MAQUINAS LTDA',
      '01.716.186/0001-42',
      'active',
      'revenda',
      'PJ',
      '(62) 3269-1100',
      NULL,
      'Avenida Independência - Quadra 20 Lote 1/3',
      '471',
      'Setor Morais',
      'Goiânia',
      'GO',
      '74620-035',
      'alto',
      'ID Legado Pedidos: 200360 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 15 | Observações: Matriz; possui varias filiais, algumas tambem em Goiania | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/01716186000142-imperial-comercio-de-parafusos-ferramentas-e-maquinas-ltda',
      NOW(),
      NOW()
    ),
(
      'INVICTO DISTRIBUIDOR LTDA',
      'INVICTO DISTRIBUIDOR LTDA',
      'INVICTO DISTRIBUIDOR LTDA',
      '03.617.629/0001-73',
      'active',
      'revenda',
      'PJ',
      '(61) 3060-0411',
      'financeiro@invictodistribuidor.com.br',
      'Avenida II - Quadra 148 Lote 21',
      'S/N',
      'Parque Alvorada I',
      'Luziânia',
      'GO',
      '72801-900',
      'alto',
      'ID Legado Pedidos: 7998683 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Planilha nao trazia cidade; empresa localizada em Luziania/GO | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/03617629000173-invicto-distribuidor-ltda',
      NOW(),
      NOW()
    ),
(
      'Proteção EPIs',
      'JOANA RODRIGUES DOS SANTOS LTDA',
      'Proteção EPIs',
      '43.320.733/0001-16',
      'active',
      'revenda',
      'PJ',
      '(64) 3623-0813',
      'protecaovendasrv@gmail.com',
      'Avenida Pauzanes de Carvalho - Quadra 40',
      '921',
      'Setor Pauzanes',
      'Rio Verde',
      'GO',
      '75903-060',
      'alto',
      'ID Legado Pedidos: 238954 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nome fantasia: Proteção EPIs | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/joana-rodrigues-dos-santos-ltda-43320733000116',
      NOW(),
      NOW()
    ),
(
      'SK EPIs',
      'K M DOS SANTOS - SK EPI''S',
      'SK EPIs',
      '39.510.487/0001-98',
      'active',
      'revenda',
      'PJ',
      '(62) 98538-5267',
      NULL,
      'Avenida Maranhão',
      '1281',
      NULL,
      'Minaçu',
      'GO',
      '76450-000',
      'alto',
      'ID Legado Pedidos: 811395 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Observações: Nome fantasia: SK EPIs | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/39510487000198-k-m-dos-santos-sk-epis',
      NOW(),
      NOW()
    ),
(
      'KAPITAO AMERICA EQUIPAMENTOS DE SEGURANCA LTDA',
      'KAPITAO AMERICA EQUIPAMENTOS DE SEGURANCA LTDA',
      'KAPITAO AMERICA EQUIPAMENTOS DE SEGURANCA LTDA',
      '00.496.983/0001-07',
      'active',
      'revenda',
      'PJ',
      '(62) 3209-5900',
      'vendas@kapitaoamerica.com.br',
      'Rua 201 - Qd 69 Lt 06',
      '66',
      NULL,
      'Goiânia',
      'GO',
      '74643-050',
      'alto',
      'ID Legado Pedidos: 188417 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 10 | Observações: Matriz; existe filial 0002-80 tambem em Goiania | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/00496983000107-KAPITAO-AMERICA-EQUIPAMENTOS-DE-SEGURANCA-LTDA',
      NOW(),
      NOW()
    ),
(
      'Brasil Mangueiras e Parafusos',
      'LG MANGUEIRAS E PARAFUSOS LTDA',
      'Brasil Mangueiras e Parafusos',
      '17.085.884/0001-27',
      'active',
      'revenda',
      'PJ',
      '(64) 3602-3131',
      'financeiropagamento@brasilmangueiras.com.br',
      'Avenida Presidente Vargas',
      '2909',
      'Vila Maria',
      'Rio Verde',
      'GO',
      '75905-310',
      'alto',
      'ID Legado Pedidos: 226308 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Observações: Nome fantasia: Brasil Mangueiras e Parafusos | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/17085884000127-lg-mangueiras-e-parafusos-ltda',
      NOW(),
      NOW()
    ),
(
      'LIDER BORRACHAS LTDA',
      'LIDER BORRACHAS LTDA',
      'LIDER BORRACHAS LTDA',
      '37.637.394/0001-01',
      'active',
      'revenda',
      'PJ',
      '(62) 3233-1662',
      NULL,
      'Avenida Anhanguera',
      '8579',
      NULL,
      'Goiânia',
      'GO',
      '74503-100',
      'alto',
      'ID Legado Pedidos: 218891 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/37637394000101-lider-borrachas-ltda',
      NOW(),
      NOW()
    ),
(
      'LOTUS DISTRIBUIDORA LTDA',
      'LOTUS DISTRIBUIDORA LTDA',
      'LOTUS DISTRIBUIDORA LTDA',
      '20.912.041/0001-61',
      'active',
      'revenda',
      'PJ',
      '(62) 98297-2808',
      'phcontabilidadego@gmail.com',
      'Avenida V 5',
      'S/N',
      'Cidade Vera Cruz',
      'Aparecida de Goiânia',
      'GO',
      '74936-600',
      'alto',
      'ID Legado Pedidos: 828282 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Observações: email da contabilidade | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/20912041000161-lotus-distribuidora-ltda',
      NOW(),
      NOW()
    ),
(
      'Hidrauflex)',
      'LTFLEX LTDA',
      'Hidrauflex)',
      '10.559.336/0001-42',
      'active',
      'revenda',
      'PJ',
      '(62) 99624-3237',
      'ja_nio2@hotmail.com',
      'Rua Barao de Maua - Quadra 41 Lote 01',
      '476',
      'Rodoviario',
      'Goiânia',
      'GO',
      '74430-090',
      'alto',
      'ID Legado Pedidos: 257861 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Observações: Matriz (nome fantasia Hidrauflex); possui filiais em Goiania: 0002-23 e 0004-95 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/10559336000142-ltflex-ltda',
      NOW(),
      NOW()
    ),
(
      'MANGUEIRAS RV PARAFUSOS E FERRAMENTAS LTDA',
      'MANGUEIRAS RV PARAFUSOS E FERRAMENTAS LTDA',
      'MANGUEIRAS RV PARAFUSOS E FERRAMENTAS LTDA',
      '28.682.246/0001-00',
      'active',
      'revenda',
      'PJ',
      '(64) 3612-4500',
      'vendasrvmangueiras@gmail.com',
      'Avenida Presidente Vargas - Quadra 40 Lote 04',
      '3415',
      'Vila Maria',
      'Rio Verde',
      'GO',
      '75905-310',
      'alto',
      'ID Legado Pedidos: 238338 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 10 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/28682246000100-mangueiras-rv-parafusos-e-ferramentas-ltda',
      NOW(),
      NOW()
    ),
(
      'Alta Protecao Epi',
      'MARCOS SILVA - EPI LTDA',
      'Alta Protecao Epi',
      '14.636.363/0001-22',
      'active',
      'revenda',
      'PJ',
      '(62) 3353-6064',
      'altaprotecaoepi@gmail.com',
      'Avenida Contorno',
      '1684',
      'Carrilho',
      'Goianésia',
      'GO',
      '76380-800',
      'alto',
      'ID Legado Pedidos: 776162 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nome fantasia: Alta Protecao Epi | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/14636363000122-marcos-silva-epi-ltda',
      NOW(),
      NOW()
    ),
(
      'MELHORES MARCAS COMERCIO E REPRESENTACOES DE FERRAMENTAS LTDA',
      'MELHORES MARCAS COMERCIO E REPRESENTACOES DE FERRAMENTAS LTDA',
      'MELHORES MARCAS COMERCIO E REPRESENTACOES DE FERRAMENTAS LTDA',
      '04.789.609/0001-42',
      'active',
      'revenda',
      'PJ',
      '(61) 3361-0044 / (61) 3051-8001',
      'melhoresmarcas@melhoresmarcas.com',
      'Setor Sia Quadra 5-C',
      'S/N',
      'Zona Industrial (Guara)',
      'Brasília',
      'DF',
      '71200-055',
      'alto',
      'ID Legado Pedidos: 922485 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Observações: Matriz; filiais 0002-23 e 0003-04 tambem em Brasilia | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/04789609000142-melhores-marcas-comercio-e-representacoes-de-ferramentas-ltda',
      NOW(),
      NOW()
    ),
(
      'MULT EPI LTDA',
      'MULT EPI LTDA',
      'MULT EPI LTDA',
      '23.269.570/0001-87',
      'active',
      'revenda',
      'PJ',
      '(64) 99605-8002',
      'contato@multepi.com.br',
      'Avenida Trinta e um de Maio',
      '221',
      'Setor Epaminondas I',
      'Jataí',
      'GO',
      '75805-150',
      'alto',
      'ID Legado Pedidos: 798752 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 6 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/23269570000187-mult-epi-ltda',
      NOW(),
      NOW()
    ),
(
      'OLIVEIRA EPIS E FERRAMENTAS LTDA',
      'OLIVEIRA EPIS E FERRAMENTAS LTDA',
      'OLIVEIRA EPIS E FERRAMENTAS LTDA',
      '37.924.082/0001-70',
      'active',
      'revenda',
      'PJ',
      '(64) 99943-3668',
      'jaquelinetome07@hotmail.com',
      'Avenida Doutor Lamartine Pinto de Avelar - Loteamento Vila Chaud',
      '250',
      NULL,
      'Catalão',
      'GO',
      '75704-020',
      'alto',
      'ID Legado Pedidos: 845955 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 6 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/37924082000170-OLIVEIRA-EPIS-E-FERRAMENTAS-LTDA',
      NOW(),
      NOW()
    ),
(
      'ORIGINAL IMPORTACAO E EXPORTACAO DE AUTO PECAS EM GERAL LTDA',
      'ORIGINAL IMPORTACAO E EXPORTACAO DE AUTO PECAS EM GERAL LTDA',
      'ORIGINAL IMPORTACAO E EXPORTACAO DE AUTO PECAS EM GERAL LTDA',
      '11.718.613/0001-85',
      'active',
      'revenda',
      'PJ',
      '(62) 3203-2622',
      'adm@viniciuspires.com.br',
      'Avenida Castelo Branco - Sala 2',
      '1601',
      NULL,
      'Goiânia',
      'GO',
      '74530-010',
      'alto',
      'ID Legado Pedidos: 259658 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: email possivelmente da contabilidade | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/11718613000185-ORIGINAL-IMPORTACAO-E-EXPORTACAO-DE-AUTO-PECAS-EM-GERAL-LTDA',
      NOW(),
      NOW()
    ),
(
      'PENTAGONO EQUIPAMENTOS DE PROTECAO INDIVIDUAL COMERCIO ATACADISTA LTDA',
      'PENTAGONO EQUIPAMENTOS DE PROTECAO INDIVIDUAL COMERCIO ATACADISTA LTDA',
      'PENTAGONO EQUIPAMENTOS DE PROTECAO INDIVIDUAL COMERCIO ATACADISTA LTDA',
      '12.450.604/0001-19',
      'active',
      'revenda',
      'PJ',
      '(62) 3209-1500',
      'atendimento@pentagonoepi.com.br',
      'Rua 224 - Quadra B Lote 2',
      '94',
      NULL,
      'Goiânia',
      'GO',
      '74643-140',
      'alto',
      'ID Legado Pedidos: 190595 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/12450604000119-pentagono-equipamentos-de-protecao-individual-comercio-atacadista-ltda',
      NOW(),
      NOW()
    ),
(
      'PERFIL EPI''S E SOLDAGEM LTDA',
      'PERFIL EPI''S E SOLDAGEM LTDA',
      'PERFIL EPI''S E SOLDAGEM LTDA',
      '05.607.740/0001-04',
      'active',
      'revenda',
      'PJ',
      '(64) 3612-2828',
      'contabilidade@perfilepis.com.br',
      'Avenida Presidente Vargas',
      '2715',
      'Jardim Goias',
      'Rio Verde',
      'GO',
      '75903-290',
      'alto',
      'ID Legado Pedidos: 975897 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/05607740000104-PERFIL-EPI-S-E-SOLDAGEM-LTDA',
      NOW(),
      NOW()
    ),
(
      'Planeta Distribuidora)',
      'PLANETA FERRAMENTAS E MAQUINAS LTDA',
      'Planeta Distribuidora)',
      '19.686.372/0001-41',
      'active',
      'revenda',
      'PJ',
      '(61) 3352-1011',
      NULL,
      'Trecho Sia/Sul Trecho 03 Lotes 450/460',
      'S/N',
      'Zona Industrial (Guara)',
      'Brasília',
      'DF',
      '71200-030',
      'alto',
      'ID Legado Pedidos: 328088 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Observações: Matriz (nome fantasia Planeta Distribuidora); filial 0002-22 tambem em Brasilia | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/19686372000141-PLANETA-FERRAMENTAS-E-MAQUINAS-LTDA',
      NOW(),
      NOW()
    ),
(
      'PRIMEIRA LINHA COMERCIAL DE ROLAMENTOS LTDA',
      'PRIMEIRA LINHA COMERCIAL DE ROLAMENTOS LTDA',
      'PRIMEIRA LINHA COMERCIAL DE ROLAMENTOS LTDA',
      '24.907.602/0001-95',
      'active',
      'revenda',
      'PJ',
      '(61) 3462-5014 / (61) 99674-1321',
      'toninhofinanceiro@1linha.com.br',
      'SIA Quadra 04C Lote 40/41',
      'S/N',
      NULL,
      'Brasília',
      'DF',
      '71200-045',
      'alto',
      'ID Legado Pedidos: 225706 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 25 | Observações: Matriz; filial 0002-76 em Brasilia e outras | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/primeira-linha-comercial-de-rolamentos-ltda-24907602000195',
      NOW(),
      NOW()
    ),
(
      'PROTECAO COMERCIO REPRESENTACAO E TREINAMENTO LTDA',
      'PROTECAO COMERCIO REPRESENTACAO E TREINAMENTO LTDA',
      'PROTECAO COMERCIO REPRESENTACAO E TREINAMENTO LTDA',
      '02.746.056/0001-15',
      'active',
      'revenda',
      'PJ',
      '(62) 3313-6464',
      'adomyjr@hotmail.com',
      'Avenida Brasil',
      '4590',
      'Calixtolandia',
      'Anápolis',
      'GO',
      '75130-630',
      'alto',
      'ID Legado Pedidos: 200386 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 2 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/02746056000115-PROTECAO-COMERCIO-REPRESENTACAO-E-TREINAMENTO-LTDA',
      NOW(),
      NOW()
    ),
(
      'Protege+ Epi',
      'PROTEGE+ DISTRIBUIDORA E SUPRIMENTOS LTDA',
      'Protege+ Epi',
      '57.991.174/0001-80',
      'active',
      'revenda',
      'PJ',
      '(62) 99287-7393',
      'financeiro.protegemaisepi@gmail.com',
      'Avenida Universitária',
      '1870',
      'Vila Santa Isabel',
      'Anápolis',
      'GO',
      '75083-350',
      'alto',
      'ID Legado Pedidos: 857643 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 12 | Observações: Nome fantasia: Protege+ Epi | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/57991174000180',
      NOW(),
      NOW()
    ),
(
      'PROTEMAX COMERCIO DE EPI''S LTDA',
      'PROTEMAX COMERCIO DE EPI''S LTDA',
      'PROTEMAX COMERCIO DE EPI''S LTDA',
      '12.268.125/0001-86',
      'active',
      'revenda',
      'PJ',
      '(62) 3277-6867',
      'protemax.adm@gmail.com',
      'Alameda Abel Soares de Castro',
      '1269',
      NULL,
      'Goiânia',
      'GO',
      '74350-020',
      'alto',
      'ID Legado Pedidos: 225045 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 7 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/12268125000186-protemax-comercio-de-epis-ltda',
      NOW(),
      NOW()
    ),
(
      'REAL BORRACHAS DE ARAGUARI LTDA',
      'REAL BORRACHAS DE ARAGUARI LTDA',
      'REAL BORRACHAS DE ARAGUARI LTDA',
      '01.717.096/0001-76',
      'active',
      'revenda',
      'PJ',
      '(34) 3241-1145',
      'diretoria@realborrachasbrasil.com',
      'Avenida Minas Gerais',
      '1543',
      'Centro',
      'Araguari',
      'MG',
      '38440-042',
      'alto',
      'ID Legado Pedidos: 305961 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Observações: Matriz em Araguari; existe filial 0002-57 em Parauapebas/PA | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/01717096000176-real-borrachas-de-araguari-ltda',
      NOW(),
      NOW()
    ),
(
      'REAL BORRACHAS LTDA',
      'REAL BORRACHAS LTDA',
      'REAL BORRACHAS LTDA',
      '18.538.446/0001-30',
      'active',
      'distribuidor',
      'PJ',
      '(64) 3411-0029',
      'diretoria@realborrachasbrasil.com',
      'Avenida Raulina Fonseca Paschoal',
      '2140',
      'Setor Central',
      'Catalão',
      'GO',
      '75701-480',
      'alto',
      'ID Legado Pedidos: 306407 | Marcas de Interesse: Nutriex + Libus | Histórico de Pedidos: 8 | Observações: Homonima em Patos de Minas/MG descartada por cidade divergente | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/18538446000130-real-borrachas-ltda',
      NOW(),
      NOW()
    ),
(
      'REAL COMERCIO BH LTDA',
      'REAL COMERCIO BH LTDA',
      'REAL COMERCIO BH LTDA',
      '50.128.951/0001-19',
      'active',
      'distribuidor',
      'PJ',
      '(64) 3411-4520',
      'diretoria@realborrachasbrasil.com',
      'Avenida Presidente Tancredo Neves',
      '5005',
      'Castelo',
      'Belo Horizonte',
      'MG',
      '31330-430',
      'alto',
      'ID Legado Pedidos: 826716 | Marcas de Interesse: Nutriex + Libus | Histórico de Pedidos: 18 | Observações: Nome bate exatamente; cadastro indica Belo Horizonte/MG, planilha dizia Contagem | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/50128951000119-real-comercio-bh-ltda',
      NOW(),
      NOW()
    ),
(
      'REAL COMERCIO DE EQUIPAMENTOS DE PROTECAO E SEGURANCA LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS DE PROTECAO E SEGURANCA LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS DE PROTECAO E SEGURANCA LTDA',
      '57.751.023/0001-55',
      'active',
      'distribuidor',
      'PJ',
      '(64) 3411-4520',
      'diretoria@realborrachasbrasil.com',
      'Avenida Central - Quadra F Lote 06 Galpao 04',
      '926',
      NULL,
      'Goiânia',
      'GO',
      '74583-350',
      'alto',
      'ID Legado Pedidos: 854928 | Marcas de Interesse: Nutriex + Libus | Histórico de Pedidos: 24 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/57751023000155-real-comercio-de-equipamentos-de-protecao-e-seguranca-ltda',
      NOW(),
      NOW()
    ),
(
      'REAL COMERCIO DE EQUIPAMENTOS DE SEGURANCA LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS DE SEGURANCA LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS DE SEGURANCA LTDA',
      '40.811.158/0001-66',
      'active',
      'distribuidor',
      'PJ',
      '(64) 3411-4520',
      'diretoria@realborrachasbrasil.com',
      'Rodovia do Mario Covas',
      '37',
      'Coqueiro',
      'Ananindeua',
      'PA',
      '67113-330',
      'alto',
      'ID Legado Pedidos: 15938 | Marcas de Interesse: Nutriex + Libus | Histórico de Pedidos: 10 | Observações: Matriz em Ananindeua; existe filial 0002-47 em Sao Luis/MA | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/40811158000166-real-comercio-de-equipamentos-de-seguranca-ltda',
      NOW(),
      NOW()
    ),
(
      'REAL COMERCIO DE EQUIPAMENTOS DE SEGURANCA LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS DE SEGURANCA LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS DE SEGURANCA LTDA',
      '40.811.158/0002-47',
      'active',
      'distribuidor',
      'PJ',
      '(64) 99205-6993',
      'diretoria@realborrachasbrasil.com',
      'Avenida Daniel de la Touche - Sala A',
      '155',
      'Vila Palmeira',
      'São Luís',
      'MA',
      '65061-020',
      'alto',
      'ID Legado Pedidos: 239022 | Marcas de Interesse: Nutriex + Libus | Histórico de Pedidos: 7 | Observações: Filial de Sao Luis; matriz 0001-66 em Ananindeua/PA (codigo 15938) | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/real-comercio-de-equipamentos-de-seguranca-ltda-40811158000247',
      NOW(),
      NOW()
    ),
(
      'REAL COMERCIO DE EQUIPAMENTOS LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS LTDA',
      'REAL COMERCIO DE EQUIPAMENTOS LTDA',
      '53.958.258/0001-61',
      'active',
      'revenda',
      'PJ',
      '(94) 99288-4986',
      'diretoria@realborrachasbrasil.com',
      'Avenida Liberdade',
      's/n',
      'Vila da Paz',
      'Parauapebas',
      'PA',
      '68515-000',
      'alto',
      'ID Legado Pedidos: 842719 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/53958258000161-real-comercio-de-equipamentos-ltda',
      NOW(),
      NOW()
    ),
(
      'Real Equipamentos',
      'REAL PATROCINIO EQUIPAMENTOS LTDA',
      'Real Equipamentos',
      '32.997.511/0001-16',
      'active',
      'revenda',
      'PJ',
      '(64) 99205-6993',
      'diretoria@realborrachas.org',
      'Avenida Faria Pereira',
      '1051',
      'Constantino',
      'Patrocínio',
      'MG',
      '38747-004',
      'alto',
      'ID Legado Pedidos: 759291 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Observações: Aparecia na base de pedidos tambem como FERNANDES EQUIPAMENTOS LTDA (nome anterior); nome fantasia Real Equipamentos | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/32997511000116-real-patrocinio-equipamentos-ltda',
      NOW(),
      NOW()
    ),
(
      'REI DAS MANGUEIRAS MAQUINAS E EQUIPAMENTOS LTDA',
      'REI DAS MANGUEIRAS MAQUINAS E EQUIPAMENTOS LTDA',
      'REI DAS MANGUEIRAS MAQUINAS E EQUIPAMENTOS LTDA',
      '07.210.957/0001-01',
      'active',
      'revenda',
      'PJ',
      '(64) 3431-3153',
      'contar@contarcontabilidade.com',
      'Rua Jose Bonifacio',
      '13',
      'Novo Horizonte',
      'Itumbiara',
      'GO',
      '75532-110',
      'alto',
      'ID Legado Pedidos: 213991 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: email da contabilidade | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/07210957000101-rei-das-mangueiras-maquinas-e-equipamentos-ltda',
      NOW(),
      NOW()
    ),
(
      'REINO DA BORRACHA LTDA',
      'REINO DA BORRACHA LTDA',
      'REINO DA BORRACHA LTDA',
      '04.451.758/0001-05',
      'active',
      'revenda',
      'PJ',
      NULL,
      'reinodaborracha1@hotmail.com',
      'Avenida Castelo Branco',
      '2620',
      'Setor Campinas',
      'Goiânia',
      'GO',
      '74513-050',
      'alto',
      'ID Legado Pedidos: 217513 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 14 | Observações: Matriz; existe filial 0002-88 tambem em Goiania | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/04451758000105-reino-da-borracha-ltda',
      NOW(),
      NOW()
    ),
(
      '(provavel razao anterior)',
      'RIBEIRO SANTOS LTDA',
      '(provavel razao anterior)',
      '29.101.392/0001-67',
      'active',
      'revenda',
      'PJ',
      '(64) 3431-0510 / (64) 99999-2363',
      'legalizacao@wrcontab.com.br',
      'Rua Itaruma',
      '840',
      'Setor Planalto',
      'Itumbiara',
      'GO',
      '75533-120',
      'alto',
      'ID Legado Pedidos: 241973 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 3 | Observações: Razao social atual RIBEIRO SANTOS LTDA; SUPREMA MAQUINAS E FERRAMENTAS e nome fantasia (provavel razao anterior); email da contabilidade | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/29101392000167-ribeiro-santos-ltda',
      NOW(),
      NOW()
    ),
(
      'SAFYRA SAFETY REPRESENTACOES LTDA',
      'SAFYRA SAFETY REPRESENTACOES LTDA',
      'SAFYRA SAFETY REPRESENTACOES LTDA',
      '64.443.879/0001-29',
      'active',
      'revenda',
      'PJ',
      '(62) 99125-1873',
      'safyrasafety@gmail.com',
      'Avenida 8 E',
      'S/N',
      'Garavelo Residencial Park',
      'Aparecida de Goiânia',
      'GO',
      '74932-250',
      'alto',
      'ID Legado Pedidos: 7996393 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Observações: E a propria Safyra (venda interna?) | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/safyra-safety-representacoes-ltda-64443879000129',
      NOW(),
      NOW()
    ),
(
      'Posto Sansao',
      'SANSAO COMERCIO DE COMBUSTIVEL LTDA',
      'Posto Sansao',
      '31.761.110/0001-08',
      'active',
      'revenda',
      'PJ',
      '(61) 3622-4525',
      NULL,
      'Avenida Alfredo Nasser',
      'S/N',
      'Parque Estrela Dalva I',
      'Luziânia',
      'GO',
      '72804-010',
      'alto',
      'ID Legado Pedidos: 260183 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nome fantasia: Posto Sansao | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/31761110000108-SANSAO-COMERCIO-DE-COMBUSTIVEL-LTDA',
      NOW(),
      NOW()
    ),
(
      'CLEAN LIMPEZA',
      'SOLUCAO MAT. LIMPEZA, HIGIENE, FERRAMENTAS E EPI LTDA',
      'CLEAN LIMPEZA',
      '22.633.039/0001-89',
      'active',
      'revenda',
      'PJ',
      '(62) 99262-9933',
      'gerente@cleanlimpezago.com.br',
      'Rua C159, Quadra267 Lote 07',
      '321',
      'Jardim America',
      'Goiânia',
      'GO',
      '74255-140',
      'baixo',
      'ID Legado Pedidos: 237485 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Nao encontrado nas bases indexadas apos varias buscas',
      NOW(),
      NOW()
    ),
(
      'SOLUFLEX SOLUCAO EM FLEXIVEIS LTDA',
      'SOLUFLEX SOLUCAO EM FLEXIVEIS LTDA',
      'SOLUFLEX SOLUCAO EM FLEXIVEIS LTDA',
      '09.333.355/0001-77',
      'active',
      'revenda',
      'PJ',
      '(64) 3632-6226',
      'maurofilho@soluflex.net.br',
      'Avenida Said Abdalla',
      '121',
      'Vila Jardim Rio Claro',
      'Jataí',
      'GO',
      '75802-030',
      'alto',
      'ID Legado Pedidos: 739376 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Matriz; existe filial 0003-39 tambem em Jatai | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/09333355000177-soluflex-solucao-em-flexiveis-ltda',
      NOW(),
      NOW()
    ),
(
      'BC Ferramentaria',
      'TERRA UTIL -COMERCIO DE MAQUINAS, FERRAMENTAS E UTILIDADES LTDA',
      'BC Ferramentaria',
      '07.144.507/0001-68',
      'active',
      'revenda',
      'PJ',
      '(61) 3701-7003 / (61) 3701-7016',
      'fiscal@bcferramentaria.com.br',
      'Trecho SIA Trecho 3',
      'S/N',
      'Zona Industrial (Guara)',
      'Brasília',
      'DF',
      '71200-030',
      'alto',
      'ID Legado Pedidos: 338765 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Observações: Matriz; existe filial 0002-49 tambem em Brasilia; nome fantasia BC Ferramentaria | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/07144507000168-terra-util-comercio-de-maquinas-ferramentas-e-utilidades-ltda',
      NOW(),
      NOW()
    ),
(
      'TH ATACADISTA DE MATERIAIS PARA CONSTRUCAO LTDA',
      'TH ATACADISTA DE MATERIAIS PARA CONSTRUCAO LTDA',
      'TH ATACADISTA DE MATERIAIS PARA CONSTRUCAO LTDA',
      '32.427.810/0001-15',
      'active',
      'revenda',
      'PJ',
      '(62) 3271-7107',
      'thchavesdistribuidora@hotmail.com',
      'Rua 52',
      '112',
      'Setor Santos Dumont',
      'Goiânia',
      'GO',
      '74463-820',
      'alto',
      'ID Legado Pedidos: 313 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 4 | Observações: CNPJ confirmado em apenas uma fonte (Solutudo); conferir | Fonte Econodata/Receita: https://solutudo.com.br/go/goiania/materiais-para-construcao/th-atacadista-5304882',
      NOW(),
      NOW()
    ),
(
      'TOP FIX PRODUTOS AUTOMOTIVOS LTDA',
      'TOP FIX PRODUTOS AUTOMOTIVOS LTDA',
      'TOP FIX PRODUTOS AUTOMOTIVOS LTDA',
      '21.717.363/0001-12',
      'active',
      'revenda',
      'PJ',
      '(62) 3413-5854',
      'financeiro@topfixautomotivos.com.br',
      'Rua 255',
      '141',
      NULL,
      'Goiânia',
      'GO',
      '74533-150',
      'alto',
      'ID Legado Pedidos: 242840 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/21717363000112-top-fix-produtos-automotivos-ltda',
      NOW(),
      NOW()
    ),
(
      'TOTAL SEGURANCA EQUIPAMENTOS DE PROTECAO E SERVICOS ESPECIALIZADOS LTDA',
      'TOTAL SEGURANCA EQUIPAMENTOS DE PROTECAO E SERVICOS ESPECIALIZADOS LTDA',
      'TOTAL SEGURANCA EQUIPAMENTOS DE PROTECAO E SERVICOS ESPECIALIZADOS LTDA',
      '13.851.726/0001-80',
      'active',
      'revenda',
      'PJ',
      '(64) 3661-2454',
      'totalseguranca@totalseguranca.net',
      'Rua Quinze',
      '47',
      'Setor Machado',
      'Mineiros',
      'GO',
      '75830-132',
      'alto',
      'ID Legado Pedidos: 313098 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/13851726000180-total-seguranca-equipamentos-de-protecao-e-servicos-especializados-ltda',
      NOW(),
      NOW()
    ),
(
      '''Goias Ferramentas''',
      'VALTER RAMOS LTDA',
      '''Goias Ferramentas''',
      '09.497.806/0001-01',
      'active',
      'revenda',
      'PJ',
      '(64) 3661-1801',
      'financeiro@goiasferramentas.com.br',
      'Avenida Antonio Carlos Paniago - Quadra 07 Loja 17',
      '21',
      'Mineirinho',
      'Mineiros',
      'GO',
      '75830-002',
      'medio',
      'ID Legado Pedidos: 211037 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Razao social atual VALTER RAMOS LTDA, nome fantasia ''''Goias Ferramentas''''; provavel alteracao da antiga razao GOIAS FERRAMENTAS EIRELI | Fonte Econodata/Receita: https://www.econodata.com.br/consulta-empresa/09497806000101-valter-ramos-ltda',
      NOW(),
      NOW()
    ),
(
      'FERRAGISTA MEGA EPI',
      'W. G. SOARES',
      'FERRAGISTA MEGA EPI',
      '08.695.331/0001-03',
      'active',
      'revenda',
      'PJ',
      '62 981571801',
      'WATSON.SOARES@HOTMAIL.COM',
      'AVENIDA BELA VISTA, QUADRA009 LOTE 0005',
      'S/N',
      'JARDIM BELA VISTA',
      'Aparecida de Goiânia',
      'GO',
      '74912-261',
      'alto',
      'ID Legado Pedidos: 209536 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 5 | Observações: Nao encontrado; empresario individual com iniciais e dificil de indexar; consultar no ERP/Sintegra',
      NOW(),
      NOW()
    ),
(
      'WORLD SEG PRODUTOS PARA SEGURANCA LTDA',
      'WORLD SEG PRODUTOS PARA SEGURANCA LTDA',
      'WORLD SEG PRODUTOS PARA SEGURANCA LTDA',
      '02.311.428/0003-42',
      'active',
      'distribuidor',
      'PJ',
      '(62) 3942-7815',
      'falecom@worldseg.com.br',
      'Avenida Vera Cruz - Quadra 34A Lote 05-08',
      '503',
      'Jardim Guanabara',
      'Goiânia',
      'GO',
      '74675-830',
      'alto',
      'ID Legado Pedidos: 222570 | Marcas de Interesse: Nutriex + Libus | Histórico de Pedidos: 26 | Observações: Filial de Goiânia; matriz 0001-80 | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/world-seg-produtos-para-seguranca-ltda-02311428000342',
      NOW(),
      NOW()
    ),
(
      'WORLD SEG PRODUTOS PARA SEGURANCA LTDA',
      'WORLD SEG PRODUTOS PARA SEGURANCA LTDA',
      'WORLD SEG PRODUTOS PARA SEGURANCA LTDA',
      '02.311.428/0002-61',
      'active',
      'revenda',
      'PJ',
      '(64) 3442-6699',
      NULL,
      'Rua Ercílio de Lima - Sala 01',
      '444',
      'Nossa Senhora de Fátima',
      'Catalão',
      'GO',
      '75709-170',
      'alto',
      'ID Legado Pedidos: 200303 | Marcas de Interesse: Nutriex Profissional | Histórico de Pedidos: 1 | Observações: Filial de Catalão | Fonte Econodata/Receita: https://casadosdados.com.br/solucao/cnpj/world-seg-produtos-para-seguranca-ltda-02311428000261',
      NOW(),
      NOW()
    ) ON CONFLICT DO NOTHING;