/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as CampoMapaRouteImport } from './routes/campo/mapa'
import { Route as CampoRoteirizacaoRouteImport } from './routes/campo/roteirizacao'
import { Route as CampoVisitasRouteImport } from './routes/campo/visitas'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes/$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes/novo'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes/index'
import { Route as ConfiguracoesAuditoriaRouteImport } from './routes/configuracoes/auditoria'
import { Route as ConfiguracoesCategoriasRouteImport } from './routes/configuracoes/categorias'
import { Route as ConfiguracoesEmpresaRouteImport } from './routes/configuracoes/empresa'
import { Route as ConfiguracoesFabricantesRouteImport } from './routes/configuracoes/fabricantes'
import { Route as ConfiguracoesNotificacoesRouteImport } from './routes/configuracoes/notificacoes'
import { Route as ConfiguracoesPermissoesRouteImport } from './routes/configuracoes/permissoes'
import { Route as ConfiguracoesPreferenciasRouteImport } from './routes/configuracoes/preferencias'
import { Route as ConfiguracoesStatusRouteImport } from './routes/configuracoes/status'
import { Route as RegioesIndexRouteImport } from './routes/regioes/index'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios/index'
import { Route as RepresentantesIndexRouteImport } from './routes/representantes/index'
import { Route as RepresentantesIdRouteImport } from './routes/representantes/$id'
import { Route as CampoVisitasNovoRouteImport } from './routes/campo/visitas/novo'
import { Route as ComercialComissoesIndexRouteImport } from './routes/comercial/comissoes/index'
import { Route as ComercialMetasIndexRouteImport } from './routes/comercial/metas/index'
import { Route as ComercialOportunidadesIndexRouteImport } from './routes/comercial/oportunidades/index'
import { Route as ComercialOportunidadesIdRouteImport } from './routes/comercial/oportunidades/$id'
import { Route as ComercialPedidosIndexRouteImport } from './routes/comercial/pedidos/index'
import { Route as ComercialPedidosIdRouteImport } from './routes/comercial/pedidos/$id'
import { Route as ComercialPedidosNovoRouteImport } from './routes/comercial/pedidos/novo'
import { Route as ComercialProdutosIndexRouteImport } from './routes/comercial/produtos/index'
import { Route as ComercialProdutosIdRouteImport } from './routes/comercial/produtos/$id'
import { Route as ComercialProdutosCategoriasRouteImport } from './routes/comercial/produtos/categorias'
import { Route as ComercialProdutosNovoRouteImport } from './routes/comercial/produtos/novo'
import { Route as ComercialTabelasDePrecoIndexRouteImport } from './routes/comercial/tabelas-de-preco/index'
import { Route as ComercialTabelasDePrecoIdRouteImport } from './routes/comercial/tabelas-de-preco/$id'
import { Route as ConfiguracoesImplantacaoIndexRouteImport } from './routes/configuracoes/implantacao/index'
import { Route as ConfiguracoesImplantacaoIdRouteImport } from './routes/configuracoes/implantacao/$id'
import { Route as ConfiguracoesImplantacaoNovaRouteImport } from './routes/configuracoes/implantacao/nova'
import { Route as ConfiguracoesRegioesIndexRouteImport } from './routes/configuracoes/regioes/index'
import { Route as ConfiguracoesUsuariosIndexRouteImport } from './routes/configuracoes/usuarios/index'
import { Route as ConfiguracoesUsuariosIdRouteImport } from './routes/configuracoes/usuarios/$id'
import { Route as ConfiguracoesUsuariosNovoRouteImport } from './routes/configuracoes/usuarios/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const CampoMapaRoute = CampoMapaRouteImport.update({
  id: '/campo/mapa',
  path: '/campo/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoRoteirizacaoRoute = CampoRoteirizacaoRouteImport.update({
  id: '/campo/roteirizacao',
  path: '/campo/roteirizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoVisitasRoute = CampoVisitasRouteImport.update({
  id: '/campo/visitas',
  path: '/campo/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesAuditoriaRoute = ConfiguracoesAuditoriaRouteImport.update({
  id: '/configuracoes/auditoria',
  path: '/configuracoes/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesCategoriasRoute = ConfiguracoesCategoriasRouteImport.update({
  id: '/configuracoes/categorias',
  path: '/configuracoes/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesEmpresaRoute = ConfiguracoesEmpresaRouteImport.update({
  id: '/configuracoes/empresa',
  path: '/configuracoes/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesFabricantesRoute =
  ConfiguracoesFabricantesRouteImport.update({
    id: '/configuracoes/fabricantes',
    path: '/configuracoes/fabricantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesNotificacoesRoute =
  ConfiguracoesNotificacoesRouteImport.update({
    id: '/configuracoes/notificacoes',
    path: '/configuracoes/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesPermissoesRoute = ConfiguracoesPermissoesRouteImport.update({
  id: '/configuracoes/permissoes',
  path: '/configuracoes/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPreferenciasRoute =
  ConfiguracoesPreferenciasRouteImport.update({
    id: '/configuracoes/preferencias',
    path: '/configuracoes/preferencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesStatusRoute = ConfiguracoesStatusRouteImport.update({
  id: '/configuracoes/status',
  path: '/configuracoes/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RegioesIndexRoute = RegioesIndexRouteImport.update({
  id: '/regioes/',
  path: '/regioes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesIndexRoute = RepresentantesIndexRouteImport.update({
  id: '/representantes/',
  path: '/representantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesIdRoute = RepresentantesIdRouteImport.update({
  id: '/representantes/$id',
  path: '/representantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoVisitasNovoRoute = CampoVisitasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => CampoVisitasRoute,
} as any)
const ComercialComissoesIndexRoute = ComercialComissoesIndexRouteImport.update({
  id: '/comercial/comissoes/',
  path: '/comercial/comissoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialMetasIndexRoute = ComercialMetasIndexRouteImport.update({
  id: '/comercial/metas/',
  path: '/comercial/metas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialOportunidadesIndexRoute =
  ComercialOportunidadesIndexRouteImport.update({
    id: '/comercial/oportunidades/',
    path: '/comercial/oportunidades/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComercialOportunidadesIdRoute =
  ComercialOportunidadesIdRouteImport.update({
    id: '/comercial/oportunidades/$id',
    path: '/comercial/oportunidades/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComercialPedidosIndexRoute = ComercialPedidosIndexRouteImport.update({
  id: '/comercial/pedidos/',
  path: '/comercial/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialPedidosIdRoute = ComercialPedidosIdRouteImport.update({
  id: '/comercial/pedidos/$id',
  path: '/comercial/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialPedidosNovoRoute = ComercialPedidosNovoRouteImport.update({
  id: '/comercial/pedidos/novo',
  path: '/comercial/pedidos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProdutosIndexRoute = ComercialProdutosIndexRouteImport.update({
  id: '/comercial/produtos/',
  path: '/comercial/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProdutosIdRoute = ComercialProdutosIdRouteImport.update({
  id: '/comercial/produtos/$id',
  path: '/comercial/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProdutosCategoriasRoute =
  ComercialProdutosCategoriasRouteImport.update({
    id: '/comercial/produtos/categorias',
    path: '/comercial/produtos/categorias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComercialProdutosNovoRoute = ComercialProdutosNovoRouteImport.update({
  id: '/comercial/produtos/novo',
  path: '/comercial/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialTabelasDePrecoIndexRoute =
  ComercialTabelasDePrecoIndexRouteImport.update({
    id: '/comercial/tabelas-de-preco/',
    path: '/comercial/tabelas-de-preco/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComercialTabelasDePrecoIdRoute =
  ComercialTabelasDePrecoIdRouteImport.update({
    id: '/comercial/tabelas-de-preco/$id',
    path: '/comercial/tabelas-de-preco/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesImplantacaoIndexRoute =
  ConfiguracoesImplantacaoIndexRouteImport.update({
    id: '/configuracoes/implantacao/',
    path: '/configuracoes/implantacao/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesImplantacaoIdRoute =
  ConfiguracoesImplantacaoIdRouteImport.update({
    id: '/configuracoes/implantacao/$id',
    path: '/configuracoes/implantacao/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesImplantacaoNovaRoute =
  ConfiguracoesImplantacaoNovaRouteImport.update({
    id: '/configuracoes/implantacao/nova',
    path: '/configuracoes/implantacao/nova',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesRegioesIndexRoute =
  ConfiguracoesRegioesIndexRouteImport.update({
    id: '/configuracoes/regioes/',
    path: '/configuracoes/regioes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesUsuariosIndexRoute =
  ConfiguracoesUsuariosIndexRouteImport.update({
    id: '/configuracoes/usuarios/',
    path: '/configuracoes/usuarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesUsuariosIdRoute = ConfiguracoesUsuariosIdRouteImport.update({
  id: '/configuracoes/usuarios/$id',
  path: '/configuracoes/usuarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesUsuariosNovoRoute =
  ConfiguracoesUsuariosNovoRouteImport.update({
    id: '/configuracoes/usuarios/novo',
    path: '/configuracoes/usuarios/novo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/campo/mapa': typeof CampoMapaRoute
  '/campo/roteirizacao': typeof CampoRoteirizacaoRoute
  '/campo/visitas': typeof CampoVisitasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/configuracoes/auditoria': typeof ConfiguracoesAuditoriaRoute
  '/configuracoes/categorias': typeof ConfiguracoesCategoriasRoute
  '/configuracoes/empresa': typeof ConfiguracoesEmpresaRoute
  '/configuracoes/fabricantes': typeof ConfiguracoesFabricantesRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/preferencias': typeof ConfiguracoesPreferenciasRoute
  '/configuracoes/status': typeof ConfiguracoesStatusRoute
  '/representantes/$id': typeof RepresentantesIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/regioes/': typeof RegioesIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/representantes/': typeof RepresentantesIndexRoute
  '/campo/visitas/novo': typeof CampoVisitasNovoRoute
  '/comercial/oportunidades/$id': typeof ComercialOportunidadesIdRoute
  '/comercial/pedidos/$id': typeof ComercialPedidosIdRoute
  '/comercial/pedidos/novo': typeof ComercialPedidosNovoRoute
  '/comercial/produtos/$id': typeof ComercialProdutosIdRoute
  '/comercial/produtos/categorias': typeof ComercialProdutosCategoriasRoute
  '/comercial/produtos/novo': typeof ComercialProdutosNovoRoute
  '/comercial/tabelas-de-preco/$id': typeof ComercialTabelasDePrecoIdRoute
  '/configuracoes/implantacao/$id': typeof ConfiguracoesImplantacaoIdRoute
  '/configuracoes/implantacao/nova': typeof ConfiguracoesImplantacaoNovaRoute
  '/configuracoes/usuarios/$id': typeof ConfiguracoesUsuariosIdRoute
  '/configuracoes/usuarios/novo': typeof ConfiguracoesUsuariosNovoRoute
  '/comercial/comissoes/': typeof ComercialComissoesIndexRoute
  '/comercial/metas/': typeof ComercialMetasIndexRoute
  '/comercial/oportunidades/': typeof ComercialOportunidadesIndexRoute
  '/comercial/pedidos/': typeof ComercialPedidosIndexRoute
  '/comercial/produtos/': typeof ComercialProdutosIndexRoute
  '/comercial/tabelas-de-preco/': typeof ComercialTabelasDePrecoIndexRoute
  '/configuracoes/implantacao/': typeof ConfiguracoesImplantacaoIndexRoute
  '/configuracoes/regioes/': typeof ConfiguracoesRegioesIndexRoute
  '/configuracoes/usuarios/': typeof ConfiguracoesUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/campo/mapa': typeof CampoMapaRoute
  '/campo/roteirizacao': typeof CampoRoteirizacaoRoute
  '/campo/visitas': typeof CampoVisitasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/configuracoes/auditoria': typeof ConfiguracoesAuditoriaRoute
  '/configuracoes/categorias': typeof ConfiguracoesCategoriasRoute
  '/configuracoes/empresa': typeof ConfiguracoesEmpresaRoute
  '/configuracoes/fabricantes': typeof ConfiguracoesFabricantesRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/preferencias': typeof ConfiguracoesPreferenciasRoute
  '/configuracoes/status': typeof ConfiguracoesStatusRoute
  '/representantes/$id': typeof RepresentantesIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/regioes': typeof RegioesIndexRoute
  '/relatorios': typeof RelatoriosIndexRoute
  '/representantes': typeof RepresentantesIndexRoute
  '/campo/visitas/novo': typeof CampoVisitasNovoRoute
  '/comercial/oportunidades/$id': typeof ComercialOportunidadesIdRoute
  '/comercial/pedidos/$id': typeof ComercialPedidosIdRoute
  '/comercial/pedidos/novo': typeof ComercialPedidosNovoRoute
  '/comercial/produtos/$id': typeof ComercialProdutosIdRoute
  '/comercial/produtos/categorias': typeof ComercialProdutosCategoriasRoute
  '/comercial/produtos/novo': typeof ComercialProdutosNovoRoute
  '/comercial/tabelas-de-preco/$id': typeof ComercialTabelasDePrecoIdRoute
  '/configuracoes/implantacao/$id': typeof ConfiguracoesImplantacaoIdRoute
  '/configuracoes/implantacao/nova': typeof ConfiguracoesImplantacaoNovaRoute
  '/configuracoes/usuarios/$id': typeof ConfiguracoesUsuariosIdRoute
  '/configuracoes/usuarios/novo': typeof ConfiguracoesUsuariosNovoRoute
  '/comercial/comissoes': typeof ComercialComissoesIndexRoute
  '/comercial/metas': typeof ComercialMetasIndexRoute
  '/comercial/oportunidades': typeof ComercialOportunidadesIndexRoute
  '/comercial/pedidos': typeof ComercialPedidosIndexRoute
  '/comercial/produtos': typeof ComercialProdutosIndexRoute
  '/comercial/tabelas-de-preco': typeof ComercialTabelasDePrecoIndexRoute
  '/configuracoes/implantacao': typeof ConfiguracoesImplantacaoIndexRoute
  '/configuracoes/regioes': typeof ConfiguracoesRegioesIndexRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/minha-conta': typeof MinhaContaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/campo/mapa': typeof CampoMapaRoute
  '/campo/roteirizacao': typeof CampoRoteirizacaoRoute
  '/campo/visitas': typeof CampoVisitasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/configuracoes/auditoria': typeof ConfiguracoesAuditoriaRoute
  '/configuracoes/categorias': typeof ConfiguracoesCategoriasRoute
  '/configuracoes/empresa': typeof ConfiguracoesEmpresaRoute
  '/configuracoes/fabricantes': typeof ConfiguracoesFabricantesRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/preferencias': typeof ConfiguracoesPreferenciasRoute
  '/configuracoes/status': typeof ConfiguracoesStatusRoute
  '/representantes/$id': typeof RepresentantesIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/regioes/': typeof RegioesIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/representantes/': typeof RepresentantesIndexRoute
  '/campo/visitas/novo': typeof CampoVisitasNovoRoute
  '/comercial/oportunidades/$id': typeof ComercialOportunidadesIdRoute
  '/comercial/pedidos/$id': typeof ComercialPedidosIdRoute
  '/comercial/pedidos/novo': typeof ComercialPedidosNovoRoute
  '/comercial/produtos/$id': typeof ComercialProdutosIdRoute
  '/comercial/produtos/categorias': typeof ComercialProdutosCategoriasRoute
  '/comercial/produtos/novo': typeof ComercialProdutosNovoRoute
  '/comercial/tabelas-de-preco/$id': typeof ComercialTabelasDePrecoIdRoute
  '/configuracoes/implantacao/$id': typeof ConfiguracoesImplantacaoIdRoute
  '/configuracoes/implantacao/nova': typeof ConfiguracoesImplantacaoNovaRoute
  '/configuracoes/usuarios/$id': typeof ConfiguracoesUsuariosIdRoute
  '/configuracoes/usuarios/novo': typeof ConfiguracoesUsuariosNovoRoute
  '/comercial/comissoes/': typeof ComercialComissoesIndexRoute
  '/comercial/metas/': typeof ComercialMetasIndexRoute
  '/comercial/oportunidades/': typeof ComercialOportunidadesIndexRoute
  '/comercial/pedidos/': typeof ComercialPedidosIndexRoute
  '/comercial/produtos/': typeof ComercialProdutosIndexRoute
  '/comercial/tabelas-de-preco/': typeof ComercialTabelasDePrecoIndexRoute
  '/configuracoes/implantacao/': typeof ConfiguracoesImplantacaoIndexRoute
  '/configuracoes/regioes/': typeof ConfiguracoesRegioesIndexRoute
  '/configuracoes/usuarios/': typeof ConfiguracoesUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/minha-conta'
    | '/notificacoes'
    | '/auth/reset-password'
    | '/campo/mapa'
    | '/campo/roteirizacao'
    | '/campo/visitas'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/configuracoes/auditoria'
    | '/configuracoes/categorias'
    | '/configuracoes/empresa'
    | '/configuracoes/fabricantes'
    | '/configuracoes/notificacoes'
    | '/configuracoes/permissoes'
    | '/configuracoes/preferencias'
    | '/configuracoes/status'
    | '/representantes/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/regioes/'
    | '/relatorios/'
    | '/representantes/'
    | '/campo/visitas/novo'
    | '/comercial/oportunidades/$id'
    | '/comercial/pedidos/$id'
    | '/comercial/pedidos/novo'
    | '/comercial/produtos/$id'
    | '/comercial/produtos/categorias'
    | '/comercial/produtos/novo'
    | '/comercial/tabelas-de-preco/$id'
    | '/configuracoes/implantacao/$id'
    | '/configuracoes/implantacao/nova'
    | '/configuracoes/usuarios/$id'
    | '/configuracoes/usuarios/novo'
    | '/comercial/comissoes/'
    | '/comercial/metas/'
    | '/comercial/oportunidades/'
    | '/comercial/pedidos/'
    | '/comercial/produtos/'
    | '/comercial/tabelas-de-preco/'
    | '/configuracoes/implantacao/'
    | '/configuracoes/regioes/'
    | '/configuracoes/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/minha-conta'
    | '/notificacoes'
    | '/auth/reset-password'
    | '/campo/mapa'
    | '/campo/roteirizacao'
    | '/campo/visitas'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/configuracoes/auditoria'
    | '/configuracoes/categorias'
    | '/configuracoes/empresa'
    | '/configuracoes/fabricantes'
    | '/configuracoes/notificacoes'
    | '/configuracoes/permissoes'
    | '/configuracoes/preferencias'
    | '/configuracoes/status'
    | '/representantes/$id'
    | '/clientes'
    | '/configuracoes'
    | '/regioes'
    | '/relatorios'
    | '/representantes'
    | '/campo/visitas/novo'
    | '/comercial/oportunidades/$id'
    | '/comercial/pedidos/$id'
    | '/comercial/pedidos/novo'
    | '/comercial/produtos/$id'
    | '/comercial/produtos/categorias'
    | '/comercial/produtos/novo'
    | '/comercial/tabelas-de-preco/$id'
    | '/configuracoes/implantacao/$id'
    | '/configuracoes/implantacao/nova'
    | '/configuracoes/usuarios/$id'
    | '/configuracoes/usuarios/novo'
    | '/comercial/comissoes'
    | '/comercial/metas'
    | '/comercial/oportunidades'
    | '/comercial/pedidos'
    | '/comercial/produtos'
    | '/comercial/tabelas-de-preco'
    | '/configuracoes/implantacao'
    | '/configuracoes/regioes'
    | '/configuracoes/usuarios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/minha-conta'
    | '/notificacoes'
    | '/auth/reset-password'
    | '/campo/mapa'
    | '/campo/roteirizacao'
    | '/campo/visitas'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/configuracoes/auditoria'
    | '/configuracoes/categorias'
    | '/configuracoes/empresa'
    | '/configuracoes/fabricantes'
    | '/configuracoes/notificacoes'
    | '/configuracoes/permissoes'
    | '/configuracoes/preferencias'
    | '/configuracoes/status'
    | '/representantes/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/regioes/'
    | '/relatorios/'
    | '/representantes/'
    | '/campo/visitas/novo'
    | '/comercial/oportunidades/$id'
    | '/comercial/pedidos/$id'
    | '/comercial/pedidos/novo'
    | '/comercial/produtos/$id'
    | '/comercial/produtos/categorias'
    | '/comercial/produtos/novo'
    | '/comercial/tabelas-de-preco/$id'
    | '/configuracoes/implantacao/$id'
    | '/configuracoes/implantacao/nova'
    | '/configuracoes/usuarios/$id'
    | '/configuracoes/usuarios/novo'
    | '/comercial/comissoes/'
    | '/comercial/metas/'
    | '/comercial/oportunidades/'
    | '/comercial/pedidos/'
    | '/comercial/produtos/'
    | '/comercial/tabelas-de-preco/'
    | '/configuracoes/implantacao/'
    | '/configuracoes/regioes/'
    | '/configuracoes/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MinhaContaRoute: typeof MinhaContaRoute
  NotificacoesRoute: typeof NotificacoesRoute
  CampoMapaRoute: typeof CampoMapaRoute
  CampoRoteirizacaoRoute: typeof CampoRoteirizacaoRoute
  CampoVisitasRoute: typeof CampoVisitasRouteWithChildren
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
  ConfiguracoesAuditoriaRoute: typeof ConfiguracoesAuditoriaRoute
  ConfiguracoesCategoriasRoute: typeof ConfiguracoesCategoriasRoute
  ConfiguracoesEmpresaRoute: typeof ConfiguracoesEmpresaRoute
  ConfiguracoesFabricantesRoute: typeof ConfiguracoesFabricantesRoute
  ConfiguracoesNotificacoesRoute: typeof ConfiguracoesNotificacoesRoute
  ConfiguracoesPermissoesRoute: typeof ConfiguracoesPermissoesRoute
  ConfiguracoesPreferenciasRoute: typeof ConfiguracoesPreferenciasRoute
  ConfiguracoesStatusRoute: typeof ConfiguracoesStatusRoute
  RepresentantesIdRoute: typeof RepresentantesIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  RegioesIndexRoute: typeof RegioesIndexRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
  RepresentantesIndexRoute: typeof RepresentantesIndexRoute
  ComercialOportunidadesIdRoute: typeof ComercialOportunidadesIdRoute
  ComercialPedidosIdRoute: typeof ComercialPedidosIdRoute
  ComercialPedidosNovoRoute: typeof ComercialPedidosNovoRoute
  ComercialProdutosIdRoute: typeof ComercialProdutosIdRoute
  ComercialProdutosCategoriasRoute: typeof ComercialProdutosCategoriasRoute
  ComercialProdutosNovoRoute: typeof ComercialProdutosNovoRoute
  ComercialTabelasDePrecoIdRoute: typeof ComercialTabelasDePrecoIdRoute
  ConfiguracoesImplantacaoIdRoute: typeof ConfiguracoesImplantacaoIdRoute
  ConfiguracoesImplantacaoNovaRoute: typeof ConfiguracoesImplantacaoNovaRoute
  ConfiguracoesUsuariosIdRoute: typeof ConfiguracoesUsuariosIdRoute
  ConfiguracoesUsuariosNovoRoute: typeof ConfiguracoesUsuariosNovoRoute
  ComercialComissoesIndexRoute: typeof ComercialComissoesIndexRoute
  ComercialMetasIndexRoute: typeof ComercialMetasIndexRoute
  ComercialOportunidadesIndexRoute: typeof ComercialOportunidadesIndexRoute
  ComercialPedidosIndexRoute: typeof ComercialPedidosIndexRoute
  ComercialProdutosIndexRoute: typeof ComercialProdutosIndexRoute
  ComercialTabelasDePrecoIndexRoute: typeof ComercialTabelasDePrecoIndexRoute
  ConfiguracoesImplantacaoIndexRoute: typeof ConfiguracoesImplantacaoIndexRoute
  ConfiguracoesRegioesIndexRoute: typeof ConfiguracoesRegioesIndexRoute
  ConfiguracoesUsuariosIndexRoute: typeof ConfiguracoesUsuariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/campo/mapa': {
      id: '/campo/mapa'
      path: '/campo/mapa'
      fullPath: '/campo/mapa'
      preLoaderRoute: typeof CampoMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/roteirizacao': {
      id: '/campo/roteirizacao'
      path: '/campo/roteirizacao'
      fullPath: '/campo/roteirizacao'
      preLoaderRoute: typeof CampoRoteirizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/visitas': {
      id: '/campo/visitas'
      path: '/campo/visitas'
      fullPath: '/campo/visitas'
      preLoaderRoute: typeof CampoVisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/auditoria': {
      id: '/configuracoes/auditoria'
      path: '/configuracoes/auditoria'
      fullPath: '/configuracoes/auditoria'
      preLoaderRoute: typeof ConfiguracoesAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/categorias': {
      id: '/configuracoes/categorias'
      path: '/configuracoes/categorias'
      fullPath: '/configuracoes/categorias'
      preLoaderRoute: typeof ConfiguracoesCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/empresa': {
      id: '/configuracoes/empresa'
      path: '/configuracoes/empresa'
      fullPath: '/configuracoes/empresa'
      preLoaderRoute: typeof ConfiguracoesEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/fabricantes': {
      id: '/configuracoes/fabricantes'
      path: '/configuracoes/fabricantes'
      fullPath: '/configuracoes/fabricantes'
      preLoaderRoute: typeof ConfiguracoesFabricantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/notificacoes': {
      id: '/configuracoes/notificacoes'
      path: '/configuracoes/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof ConfiguracoesNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/permissoes': {
      id: '/configuracoes/permissoes'
      path: '/configuracoes/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof ConfiguracoesPermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/preferencias': {
      id: '/configuracoes/preferencias'
      path: '/configuracoes/preferencias'
      fullPath: '/configuracoes/preferencias'
      preLoaderRoute: typeof ConfiguracoesPreferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/status': {
      id: '/configuracoes/status'
      path: '/configuracoes/status'
      fullPath: '/configuracoes/status'
      preLoaderRoute: typeof ConfiguracoesStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioes/': {
      id: '/regioes/'
      path: '/regioes'
      fullPath: '/regioes/'
      preLoaderRoute: typeof RegioesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes/': {
      id: '/representantes/'
      path: '/representantes'
      fullPath: '/representantes/'
      preLoaderRoute: typeof RepresentantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes/$id': {
      id: '/representantes/$id'
      path: '/representantes/$id'
      fullPath: '/representantes/$id'
      preLoaderRoute: typeof RepresentantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/visitas/novo': {
      id: '/campo/visitas/novo'
      path: '/novo'
      fullPath: '/campo/visitas/novo'
      preLoaderRoute: typeof CampoVisitasNovoRouteImport
      parentRoute: typeof CampoVisitasRoute
    }
    '/comercial/comissoes/': {
      id: '/comercial/comissoes/'
      path: '/comercial/comissoes'
      fullPath: '/comercial/comissoes/'
      preLoaderRoute: typeof ComercialComissoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/metas/': {
      id: '/comercial/metas/'
      path: '/comercial/metas'
      fullPath: '/comercial/metas/'
      preLoaderRoute: typeof ComercialMetasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/oportunidades/': {
      id: '/comercial/oportunidades/'
      path: '/comercial/oportunidades'
      fullPath: '/comercial/oportunidades/'
      preLoaderRoute: typeof ComercialOportunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/oportunidades/$id': {
      id: '/comercial/oportunidades/$id'
      path: '/comercial/oportunidades/$id'
      fullPath: '/comercial/oportunidades/$id'
      preLoaderRoute: typeof ComercialOportunidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/pedidos/': {
      id: '/comercial/pedidos/'
      path: '/comercial/pedidos'
      fullPath: '/comercial/pedidos/'
      preLoaderRoute: typeof ComercialPedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/pedidos/$id': {
      id: '/comercial/pedidos/$id'
      path: '/comercial/pedidos/$id'
      fullPath: '/comercial/pedidos/$id'
      preLoaderRoute: typeof ComercialPedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/pedidos/novo': {
      id: '/comercial/pedidos/novo'
      path: '/comercial/pedidos/novo'
      fullPath: '/comercial/pedidos/novo'
      preLoaderRoute: typeof ComercialPedidosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/produtos/': {
      id: '/comercial/produtos/'
      path: '/comercial/produtos'
      fullPath: '/comercial/produtos/'
      preLoaderRoute: typeof ComercialProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/produtos/$id': {
      id: '/comercial/produtos/$id'
      path: '/comercial/produtos/$id'
      fullPath: '/comercial/produtos/$id'
      preLoaderRoute: typeof ComercialProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/produtos/categorias': {
      id: '/comercial/produtos/categorias'
      path: '/comercial/produtos/categorias'
      fullPath: '/comercial/produtos/categorias'
      preLoaderRoute: typeof ComercialProdutosCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/produtos/novo': {
      id: '/comercial/produtos/novo'
      path: '/comercial/produtos/novo'
      fullPath: '/comercial/produtos/novo'
      preLoaderRoute: typeof ComercialProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/tabelas-de-preco/': {
      id: '/comercial/tabelas-de-preco/'
      path: '/comercial/tabelas-de-preco'
      fullPath: '/comercial/tabelas-de-preco/'
      preLoaderRoute: typeof ComercialTabelasDePrecoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/tabelas-de-preco/$id': {
      id: '/comercial/tabelas-de-preco/$id'
      path: '/comercial/tabelas-de-preco/$id'
      fullPath: '/comercial/tabelas-de-preco/$id'
      preLoaderRoute: typeof ComercialTabelasDePrecoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/implantacao/': {
      id: '/configuracoes/implantacao/'
      path: '/configuracoes/implantacao'
      fullPath: '/configuracoes/implantacao/'
      preLoaderRoute: typeof ConfiguracoesImplantacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/implantacao/$id': {
      id: '/configuracoes/implantacao/$id'
      path: '/configuracoes/implantacao/$id'
      fullPath: '/configuracoes/implantacao/$id'
      preLoaderRoute: typeof ConfiguracoesImplantacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/implantacao/nova': {
      id: '/configuracoes/implantacao/nova'
      path: '/configuracoes/implantacao/nova'
      fullPath: '/configuracoes/implantacao/nova'
      preLoaderRoute: typeof ConfiguracoesImplantacaoNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/regioes/': {
      id: '/configuracoes/regioes/'
      path: '/configuracoes/regioes'
      fullPath: '/configuracoes/regioes/'
      preLoaderRoute: typeof ConfiguracoesRegioesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/usuarios/': {
      id: '/configuracoes/usuarios/'
      path: '/configuracoes/usuarios'
      fullPath: '/configuracoes/usuarios/'
      preLoaderRoute: typeof ConfiguracoesUsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/usuarios/$id': {
      id: '/configuracoes/usuarios/$id'
      path: '/configuracoes/usuarios/$id'
      fullPath: '/configuracoes/usuarios/$id'
      preLoaderRoute: typeof ConfiguracoesUsuariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/usuarios/novo': {
      id: '/configuracoes/usuarios/novo'
      path: '/configuracoes/usuarios/novo'
      fullPath: '/configuracoes/usuarios/novo'
      preLoaderRoute: typeof ConfiguracoesUsuariosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CampoVisitasRouteChildren {
  CampoVisitasNovoRoute: typeof CampoVisitasNovoRoute
}

const CampoVisitasRouteChildren: CampoVisitasRouteChildren = {
  CampoVisitasNovoRoute: CampoVisitasNovoRoute,
}

const CampoVisitasRouteWithChildren = CampoVisitasRoute._addFileChildren(
  CampoVisitasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MinhaContaRoute: MinhaContaRoute,
  NotificacoesRoute: NotificacoesRoute,
  CampoMapaRoute: CampoMapaRoute,
  CampoRoteirizacaoRoute: CampoRoteirizacaoRoute,
  CampoVisitasRoute: CampoVisitasRouteWithChildren,
  ClientesIdRoute: ClientesIdRoute,
  ClientesNovoRoute: ClientesNovoRoute,
  ConfiguracoesAuditoriaRoute: ConfiguracoesAuditoriaRoute,
  ConfiguracoesCategoriasRoute: ConfiguracoesCategoriasRoute,
  ConfiguracoesEmpresaRoute: ConfiguracoesEmpresaRoute,
  ConfiguracoesFabricantesRoute: ConfiguracoesFabricantesRoute,
  ConfiguracoesNotificacoesRoute: ConfiguracoesNotificacoesRoute,
  ConfiguracoesPermissoesRoute: ConfiguracoesPermissoesRoute,
  ConfiguracoesPreferenciasRoute: ConfiguracoesPreferenciasRoute,
  ConfiguracoesStatusRoute: ConfiguracoesStatusRoute,
  RepresentantesIdRoute: RepresentantesIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  RegioesIndexRoute: RegioesIndexRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
  RepresentantesIndexRoute: RepresentantesIndexRoute,
  ComercialOportunidadesIdRoute: ComercialOportunidadesIdRoute,
  ComercialPedidosIdRoute: ComercialPedidosIdRoute,
  ComercialPedidosNovoRoute: ComercialPedidosNovoRoute,
  ComercialProdutosIdRoute: ComercialProdutosIdRoute,
  ComercialProdutosCategoriasRoute: ComercialProdutosCategoriasRoute,
  ComercialProdutosNovoRoute: ComercialProdutosNovoRoute,
  ComercialTabelasDePrecoIdRoute: ComercialTabelasDePrecoIdRoute,
  ConfiguracoesImplantacaoIdRoute: ConfiguracoesImplantacaoIdRoute,
  ConfiguracoesImplantacaoNovaRoute: ConfiguracoesImplantacaoNovaRoute,
  ConfiguracoesUsuariosIdRoute: ConfiguracoesUsuariosIdRoute,
  ConfiguracoesUsuariosNovoRoute: ConfiguracoesUsuariosNovoRoute,
  ComercialComissoesIndexRoute: ComercialComissoesIndexRoute,
  ComercialMetasIndexRoute: ComercialMetasIndexRoute,
  ComercialOportunidadesIndexRoute: ComercialOportunidadesIndexRoute,
  ComercialPedidosIndexRoute: ComercialPedidosIndexRoute,
  ComercialProdutosIndexRoute: ComercialProdutosIndexRoute,
  ComercialTabelasDePrecoIndexRoute: ComercialTabelasDePrecoIndexRoute,
  ConfiguracoesImplantacaoIndexRoute: ConfiguracoesImplantacaoIndexRoute,
  ConfiguracoesRegioesIndexRoute: ConfiguracoesRegioesIndexRoute,
  ConfiguracoesUsuariosIndexRoute: ConfiguracoesUsuariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
