// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function clearStaleSession(supabaseUrl: string) {
  if (typeof window === 'undefined' || typeof localStorage === 'undefined') return;
  // Detect if localStorage has a session from a different Supabase project.
  // Supabase stores the session under "sb-<project-ref>-auth-token".
  // If we find any "sb-*-auth-token" key whose project ref doesn't match
  // the current URL, remove it so the browser doesn't reuse a stale session.
  try {
    const projectRef = new URL(supabaseUrl).hostname.split('.')[0];
    Object.keys(localStorage)
      .filter(key => key.startsWith('sb-') && key.endsWith('-auth-token') && !key.startsWith(`sb-${projectRef}-`))
      .forEach(key => {
        localStorage.removeItem(key);
        console.info(`[Supabase] Removed stale session key: ${key}`);
      });
  } catch {
    // non-critical — ignore
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering) with safe fallback defaults
  const SUPABASE_URL =
    (typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env['VITE_SUPABASE_URL'] || import.meta.env['SUPABASE_URL'] : undefined) ||
    (typeof process !== 'undefined' && process.env ? process.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'] : undefined) ||
    'https://hxogosqpcewvtwdyerru.supabase.co';

  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || import.meta.env['SUPABASE_PUBLISHABLE_KEY'] || import.meta.env['VITE_SUPABASE_ANON_KEY'] : undefined) ||
    (typeof process !== 'undefined' && process.env ? process.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'] || process.env['VITE_SUPABASE_ANON_KEY'] || process.env['SUPABASE_ANON_KEY'] : undefined) ||
    'sb_publishable_rYjSijG2jpE9_ys5EZIUJA_36mbvyi5';

  // Remove any session that belongs to a different Supabase project
  // so the browser doesn't reuse a stale token from a deleted project.
  clearStaleSession(SUPABASE_URL);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

